apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cryostat.discovery: "true"
    io.cryostat.jmxHost: localhost
    io.cryostat.jmxPort: "0"
    io.cryostat.jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi
    kompose.cmd: kompose convert -o ./ -f ./../compose/db_k8s.yml -f ./../compose/s3-minio.yml -f ./../compose/cryostat_k8s.yml -f ./../compose/sample-apps.yml --build local
    kompose.service.expose: cryostat3
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: cryostat
  name: cryostat
spec:
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8181
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: cryostat
status:
  loadBalancer: {}
