apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./ -f ./../compose/db_k8s.yml -f ./../compose/s3-minio.yml -f ./../compose/cryostat_k8s.yml -f ./../compose/sample-apps.yml --build local
    kompose.service.expose: pgadmin
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: db-viewer
  name: db-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-viewer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./ -f ./../compose/db_k8s.yml -f ./../compose/s3-minio.yml -f ./../compose/cryostat_k8s.yml -f ./../compose/sample-apps.yml --build local
        kompose.service.expose: pgadmin
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: db-viewer
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@cryostat.io
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_LISTEN_PORT
              value: "8989"
          image: docker.io/dpage/pgadmin4:6
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 --spider http://localhost:8989 || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: db-viewer
          ports:
            - containerPort: 8989
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin
            - mountPath: /pgadmin4/servers.json
              name: serverjson
              subPath: servers.json
      hostname: db-viewer
      restartPolicy: Always
      volumes:
        - name: pgadmin
          persistentVolumeClaim:
            claimName: pgadmin
        - name: serverjson
          configMap:
            name: pgadmin-config
            items:
              - key: servers.json
                path: servers.json
status: {}
