apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./ -f ./../compose/db_k8s.yml -f ./../compose/s3-minio.yml -f ./../compose/cryostat_k8s.yml -f ./../compose/sample-apps.yml --build local
    kompose.service.expose: pgadmin
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: db-viewer
  name: db-viewer
spec:
  rules:
    - host: pgadmin
      http:
        paths:
          - backend:
              service:
                name: db-viewer
                port:
                  number: 8989
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
