apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cryostat.discovery: "true"
    io.cryostat.jmxHost: sample-app
    io.cryostat.jmxPort: "9093"
  creationTimestamp: null
  labels:
    io.kompose.service: sample-app
  name: sample-app
  namespace: default
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: sample-app
status:
  loadBalancer: {}
